### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by hsjdhudn** [Foxyas/Changed-Addon-Rework#5] opened 2024-02-12 04:36 UTC
addon 2.5.3 is incompatible changed:Minecraft mod 0.13

**Comment by hsjdhudn** [comment] 2024-02-12 13:00
Incompatible reason I know some, because the snow fox eyes are not custom, that is, three colors may not be Settings, changed the author of the 0.13.1 pateron version of the Settings custom color, can make the left eye and right eye color different, Iris may change, and Snow Fox did not, hope to add

**Comment by Foxyas** [comment] 2024-02-12 13:09
Already fix 
The issue is the Model That was trying to use a "non-existing" animation

And the snow fox (male and female) now have the custom eyes render and a model more similar to the main mod

**Comment by hsjdhudn** [comment] 2024-02-13 09:40
Well, is the incompatibility problem resolved to 2.5.4, and is 2.5.4 under review?

**Comment by Foxyas** [comment] 2024-02-13 19:59
> Well, is the incompatibility problem resolved to 2.5.4, and is 2.5.4 under review?
version 2.5.4 is having slight adjustments before being released but it will probably be divided into two parts, one part will be released before and the second part will be an update to version 2.54

**Closed** 2024-02-21 03:59 UTC
Labels: Already fix
